
name: test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the commit message
      run: echo "The commit message is ${{ github.event.head_commit.message }}"

    - name: determine which jobs to skip
      uses: actions/github-script@v3
      id: what-to-run
      with:
        #github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          # allow jobs to be skipped by adding [skip: a b c] to the commit message
          const skip_jobs = "${{github.event.head_commit.message}}".match(/\[skip:(.*)\]/);
          console.log(skip_jobs[1]);

          matrixJobs = ['a', 'b', 'c']
          jobsToRun = matrixJobs;

          if (skip_jobs) {
            jobsToSkip = skip_jobs[1].trim().split(' ');            
            jobsToRun = matrixJobs.filter(x => !jobsToSkip.includes(x));
          }

          //return jobsToRun;

          // set the output for the next step to the jobs to run
          return { jobsToRun: jobsToRun };

  # log-github-event-goodies:
  #   name: "LOG Everything on GitHub Event"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Logging
  #       run: |
  #         echo "${{toJSON(github.event)}}"

  another_matrix:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{fromJson(needs.build.outputs.what-to-run).jobsToRun}}
      max-parallel: 3
    steps:
    - name: Matrix ${{ matrix.name }}!
      run: echo "Hello ${{ matrix.name }}!"

  # test_matrix:
  #   strategy:
  #     matrix:
  #       name: ['a', 'b', 'c']
  #     max-parallel: 3
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run a matrix ${{ matrix.name }}!
  #     run: echo "Hello ${{ matrix.name }}!"
