
name: test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: determine which jobs to skip
      uses: actions/github-script@v3
      id: what-to-run
      with:
        #github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // allow jobs to be skipped by adding [skip: a b c] to the commit message
          const skip_jobs = "${{github.event.head_commit.message}}".match(/\[skip:(.*)\]/);
          console.log(skip_jobs[1]);

          const matrixJobs = ['a', 'b', 'c']
          let jobsToRun = matrixJobs;

          if (skip_jobs) {
            let jobsToSkip = skip_jobs[1].trim().split(' ');            
            jobsToRun = matrixJobs.filter(x => !jobsToSkip.includes(x));
          }

          return jobsToRun;

          // set the output for the next step to the jobs to run
          // return { jobs: jobsToRun };

  # another_matrix:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       name: ${{fromJson(needs.build.outputs.what-to-run).jobs}}
  #     max-parallel: 3
  #   steps:
  #   - name: Matrix ${{ matrix.name }}!
  #     run: echo "Hello ${{ matrix.name }}!"