
name: test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      run: echo "Hello, world!"

  test_matrix:
    strategy:
      matrix:
        name: ['a', 'b', 'c']
    runs-on: ubuntu-latest
    steps:
    - name: Run a matrix
      run: echo "Hello ${{ matrix.name }}!"
