
name: test1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      run: echo "Hello, world!"
    
    # a step which prints the last commit message
    - name: Get the commit message
      run: echo "The commit message is ${{ github.event.head_commit.message }}"

  test_matrix:
    strategy:
      matrix:
        name: ['a', 'b', 'c']
    runs-on: ubuntu-latest
    steps:
    - name: Run a matrix
      run: echo "Hello ${{ matrix.name }}!"
